@startuml
交易中心前置 -> 交易中心: 发起交易
交易中心 -> 权益中心: 根据订单金额获取权益成本
权益中心 -> 交易中心: 返回权益成本
交易中心 -> 交易中心: 生成交易流水号
交易中心 -> 权益中心: 发起扣减积分、权益
交易中心 --> 交易中心: 其余交易步骤出现异常
交易中心 -> 权益中心: 发起冲正
权益中心 -> 交易中心: 返回冲正结果
交易中心 -> 交易中心前置: 返回
@enduml